//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StkCommon.UI.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StkCommon.UI.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия .
        /// </summary>
        public static string AboutWindow_ApplicationVersionName {
            get {
                return ResourceManager.GetString("AboutWindow_ApplicationVersionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факс: .
        /// </summary>
        public static string AboutWindow_FaxName {
            get {
                return ResourceManager.GetString("AboutWindow_FaxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон: .
        /// </summary>
        public static string AboutWindow_PhonesName {
            get {
                return ResourceManager.GetString("AboutWindow_PhonesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        public static string AboutWindow_Title {
            get {
                return ResourceManager.GetString("AboutWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База данных.
        /// </summary>
        public static string AuthorizationWindow_DataBase {
            get {
                return ResourceManager.GetString("AuthorizationWindow_DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошло непредвиденное исключение. Доступ в систему невозможен.
        ///.
        /// </summary>
        public static string AuthorizationWindow_FaultExceptionMessage {
            get {
                return ResourceManager.GetString("AuthorizationWindow_FaultExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string AuthorizationWindow_Password {
            get {
                return ResourceManager.GetString("AuthorizationWindow_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер.
        /// </summary>
        public static string AuthorizationWindow_Server {
            get {
                return ResourceManager.GetString("AuthorizationWindow_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в систему.
        /// </summary>
        public static string AuthorizationWindow_Title {
            get {
                return ResourceManager.GetString("AuthorizationWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string AuthorizationWindow_UserName {
            get {
                return ResourceManager.GetString("AuthorizationWindow_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В ходе выполнения операции{0}произошла ошибка..
        /// </summary>
        public static string ExceptionHandlerCommand_ErrorMessage {
            get {
                return ResourceManager.GetString("ExceptionHandlerCommand_ErrorMessage", resourceCulture);
            }
        }
    }
}
